services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
