version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: compa-app-postgres
    environment:
      POSTGRES_USER: clercminator
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: compa-app
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - compa-app-network

  backend:
    build:
      context: ./backend  # Points to the Dockerfile in the backend directory
    container_name: compa-app-backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: clercminator
      DATABASE_PASSWORD: 123
      DATABASE_NAME: compa-app
    ports:
      - '5000:5000'
    depends_on:
      - postgres  # Backend service depends on PostgreSQL
    networks:
      - compa-app-network

  frontend:
    build:
      context: ./frontend  # Points to the Dockerfile in the frontend directory
    container_name: compa-app-frontend
    ports:
      - '3000:3000'
    networks:
      - compa-app-network

volumes:
  postgres-data:

networks:
  compa-app-network:
